###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Thomas J. Sargent & John Stachurski'
bibtex_bibfiles = ['_static/quant-econ.bib']
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2021'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
execution_allow_errors = False
execution_excludepatterns = []
execution_in_temp = False
execution_timeout = 600
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_panels', 'sphinx_book_theme', 'sphinx_multitoc_numbering', 'sphinxext.rediraffe', 'sphinx_tojupyter', 'sphinxcontrib.youtube', 'sphinx.ext.todo', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
html_baseurl = 'https://python.quantecon.org/'
html_favicon = '_static/lectures-favicon.ico'
html_logo = '_static/qe-logo-large.png'
html_sourcelink_suffix = ''
html_static_path = ['_static', '_static']
html_theme = 'quantecon_book_theme'
html_theme_options = {'header_organisation_url': 'https://quantecon.org', 'header_organisation': 'QuantEcon', 'repository_url': 'https://github.com/QuantEcon/lecture-python.myst', 'nb_repository_url': 'https://github.com/QuantEcon/lecture-python.notebooks', 'twitter': 'quantecon', 'twitter_logo_url': 'https://assets.quantecon.org/img/qe-twitter-logo.png', 'og_logo_url': 'https://assets.quantecon.org/img/qe-og-logo.png', 'description': 'This website presents a set of lectures on quantitative economic modeling, designed and written by Thomas J. Sargent and John Stachurski.', 'keywords': 'Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski', 'google_analytics_id': 'UA-54984338-10'}
html_title = 'Quantitative Economics with Python'
jupyter_cache = ''
jupyter_execute_notebooks = 'cache'
language = None
latex_engine = 'pdflatex'
mathjax3_config = {'tex': {'macros': {'argmax': 'arg\\,max', 'argmin': 'arg\\,min'}}}
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js'
myst_enable_extensions = ['amsmath', 'colon_fence', 'deflist', 'dollarmath', 'html_admonition', 'html_image', 'linkify', 'replacements', 'smartquotes', 'substitution']
myst_url_schemes = ['mailto', 'http', 'https']
nb_output_stderr = 'show'
nb_render_priority = {'html': ['application/vnd.jupyter.widget-view+json', 'application/javascript', 'text/html', 'text/latex', 'image/svg+xml', 'image/png', 'image/jpeg', 'text/markdown', 'text/plain'], 'jupyter': ['application/vnd.jupyter.widget-view+json', 'application/javascript', 'text/html', 'text/latex', 'image/svg+xml', 'image/png', 'image/jpeg', 'text/markdown', 'text/plain']}
numfig = True
panels_add_bootstrap_css = False
pygments_style = 'sphinx'
rediraffe_redirects = {'index_toc.md': 'intro.md'}
suppress_warnings = ['myst.domains']
tojupyter_image_urlpath = 'https://python.quantecon.org/_static/'
tojupyter_images_markdown = True
tojupyter_kernels = {'python3': {'kernelspec': {'display_name': 'Python', 'language': 'python3', 'name': 'python3'}, 'file_extension': '.py'}}
tojupyter_lang_synonyms = ['ipython', 'ipython3', 'python']
tojupyter_static_file_path = ['source/_static', '_static']
tojupyter_target_html = True
tojupyter_urlpath = 'https://python.quantecon.org/'
use_jupyterbook_latex = True
use_multitoc_numbering = True
