###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Thomas J. Sargent & John Stachurski'
bibtex_bibfiles = ['_static/quant-econ.bib']
bibtex_reference_style = 'author_year'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_multitoc_numbering', 'sphinxext.rediraffe', 'sphinx_tojupyter', 'sphinxcontrib.youtube', 'sphinx.ext.todo', 'sphinx_exercise', 'sphinx_proof', 'sphinx_reredirects', 'sphinxcontrib.bibtex', 'sphinx_jupyterbook_latex', 'sphinx_multitoc_numbering']
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
html_baseurl = 'https://python.quantecon.org/'
html_favicon = '_static/lectures-favicon.ico'
html_logo = '_static/qe-logo-large.png'
html_sourcelink_suffix = ''
html_static_path = ['_static', '_static']
html_theme = 'quantecon_book_theme'
html_theme_options = {'authors': [{'name': 'Thomas J. Sargent', 'url': 'http://www.tomsargent.com/'}, {'name': 'John Stachurski', 'url': 'https://johnstachurski.net/'}], 'header_organisation_url': 'https://quantecon.org', 'header_organisation': 'QuantEcon', 'repository_url': 'https://github.com/QuantEcon/lecture-python.myst', 'nb_repository_url': 'https://github.com/QuantEcon/lecture-python.notebooks', 'twitter': 'quantecon', 'twitter_logo_url': 'https://assets.quantecon.org/img/qe-twitter-logo.png', 'og_logo_url': 'https://assets.quantecon.org/img/qe-og-logo.png', 'description': 'This website presents a set of lectures on quantitative economic modeling, designed and written by Thomas J. Sargent and John Stachurski.', 'keywords': 'Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski', 'analytics': {'google_analytics_id': 'G-J0SMYR4SG3'}, 'launch_buttons': {'colab_url': 'https://colab.research.google.com'}}
html_title = 'Intermediate Quantitative Economics with Python'
intersphinx_mapping = {'intro': ['https://intro.quantecon.org/', None], 'advanced': ['https://python-advanced.quantecon.org', None]}
latex_engine = 'pdflatex'
linkcheck_ignore = ['https://online.stat.psu.edu/stat415/book/export/html/834']
mathjax3_config = {'tex': {'macros': {'argmax': 'arg\\,max', 'argmin': 'arg\\,min'}}}
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
myst_enable_extensions = ['amsmath', 'colon_fence', 'deflist', 'dollarmath', 'html_admonition', 'html_image', 'linkify', 'replacements', 'smartquotes', 'substitution']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'cache'
nb_execution_timeout = 2400
nb_mime_priority_overrides = [['html', 'application/vnd.jupyter.widget-view+json', 10], ['html', 'application/javascript', 20], ['html', 'text/html', 30], ['html', 'text/latex', 40], ['html', 'image/svg+xml', 50], ['html', 'image/png', 60], ['html', 'image/jpeg', 70], ['html', 'text/markdown', 80], ['html', 'text/plain', 90], ['jupyter', 'application/vnd.jupyter.widget-view+json', 10], ['jupyter', 'application/javascript', 20], ['jupyter', 'text/html', 30], ['jupyter', 'text/latex', 40], ['jupyter', 'image/svg+xml', 50], ['jupyter', 'image/png', 60], ['jupyter', 'image/jpeg', 70], ['jupyter', 'text/markdown', 80], ['jupyter', 'text/plain', 90], ['latex', 'text/latex', 10], ['latex', 'application/pdf', 20], ['latex', 'image/png', 30], ['latex', 'image/jpeg', 40], ['latex', 'text/markdown', 50], ['latex', 'text/plain', 60], ['linkcheck', 'text/plain', 10]]
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
rediraffe_redirects = {'index_toc.md': 'intro.md'}
redirects = {'heavy_tails': 'https://intro.quantecon.org/heavy_tails.html', 'ar1_processes': 'https://intro.quantecon.org/ar1_processes.html', 'geom_series': 'https://intro.quantecon.org/geom_series.html', 'lp_intro': 'https://intro.quantecon.org/lp_intro.html', 'short_path': 'https://intro.quantecon.org/short_path.html', 'schelling': 'https://intro.quantecon.org/schelling.html', 'scalar_dynam': 'https://intro.quantecon.org/scalar_dynam.html', 'complex_and_trig': 'https://intro.quantecon.org/complex_and_trig.html'}
suppress_warnings = ['myst.domains']
tojupyter_image_urlpath = 'https://python.quantecon.org/_static/'
tojupyter_images_markdown = True
tojupyter_kernels = {'python3': {'kernelspec': {'display_name': 'Python', 'language': 'python3', 'name': 'python3'}, 'file_extension': '.py'}}
tojupyter_lang_synonyms = ['ipython', 'ipython3', 'python']
tojupyter_static_file_path = ['source/_static', '_static']
tojupyter_target_html = True
tojupyter_urlpath = 'https://python.quantecon.org/'
use_jupyterbook_latex = True
use_multitoc_numbering = True
